BEGIN TRANSACTION;
CREATE TABLE 'home_character_type' ('pos_id' INTEGER NOT NULL, 'original_personality' INTEGER NOT NULL, 'change_personality' INTEGER NOT NULL, PRIMARY KEY('pos_id','original_personality'));
INSERT INTO "home_character_type" VALUES(1,1,1);
INSERT INTO "home_character_type" VALUES(1,2,2);
INSERT INTO "home_character_type" VALUES(1,3,3);
INSERT INTO "home_character_type" VALUES(1,4,1);
INSERT INTO "home_character_type" VALUES(1,5,5);
INSERT INTO "home_character_type" VALUES(2,1,1);
INSERT INTO "home_character_type" VALUES(2,2,2);
INSERT INTO "home_character_type" VALUES(2,3,3);
INSERT INTO "home_character_type" VALUES(2,4,1);
INSERT INTO "home_character_type" VALUES(2,5,2);
INSERT INTO "home_character_type" VALUES(3,1,1);
INSERT INTO "home_character_type" VALUES(3,2,2);
INSERT INTO "home_character_type" VALUES(3,3,3);
INSERT INTO "home_character_type" VALUES(3,4,1);
INSERT INTO "home_character_type" VALUES(3,5,5);
INSERT INTO "home_character_type" VALUES(4,1,1);
INSERT INTO "home_character_type" VALUES(4,2,2);
INSERT INTO "home_character_type" VALUES(4,3,3);
INSERT INTO "home_character_type" VALUES(4,4,1);
INSERT INTO "home_character_type" VALUES(4,5,2);
COMMIT;