BEGIN TRANSACTION;
CREATE TABLE 'item_group' ('id' INTEGER NOT NULL, 'group_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO "item_group" VALUES(1,2);
INSERT INTO "item_group" VALUES(4,2);
INSERT INTO "item_group" VALUES(7,2);
INSERT INTO "item_group" VALUES(10,2);
INSERT INTO "item_group" VALUES(13,2);
INSERT INTO "item_group" VALUES(69,1);
INSERT INTO "item_group" VALUES(70,1);
INSERT INTO "item_group" VALUES(71,1);
INSERT INTO "item_group" VALUES(72,1);
INSERT INTO "item_group" VALUES(73,1);
INSERT INTO "item_group" VALUES(74,1);
INSERT INTO "item_group" VALUES(75,1);
INSERT INTO "item_group" VALUES(76,1);
INSERT INTO "item_group" VALUES(77,1);
INSERT INTO "item_group" VALUES(78,1);
INSERT INTO "item_group" VALUES(79,1);
INSERT INTO "item_group" VALUES(80,1);
INSERT INTO "item_group" VALUES(81,1);
INSERT INTO "item_group" VALUES(82,1);
INSERT INTO "item_group" VALUES(83,1);
INSERT INTO "item_group" VALUES(84,1);
INSERT INTO "item_group" VALUES(85,1);
INSERT INTO "item_group" VALUES(86,1);
INSERT INTO "item_group" VALUES(87,1);
INSERT INTO "item_group" VALUES(88,1);
INSERT INTO "item_group" VALUES(89,1);
INSERT INTO "item_group" VALUES(90,1);
INSERT INTO "item_group" VALUES(91,1);
INSERT INTO "item_group" VALUES(92,1);
INSERT INTO "item_group" VALUES(101,1);
INSERT INTO "item_group" VALUES(102,1);
INSERT INTO "item_group" VALUES(103,1);
INSERT INTO "item_group" VALUES(104,1);
INSERT INTO "item_group" VALUES(105,1);
INSERT INTO "item_group" VALUES(106,1);
COMMIT;