BEGIN TRANSACTION;
CREATE TABLE 'mini_mouth_type' ('id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'reverse_mouth_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO "mini_mouth_type" VALUES(0,1,16);
INSERT INTO "mini_mouth_type" VALUES(1,1,16);
INSERT INTO "mini_mouth_type" VALUES(2,2,15);
INSERT INTO "mini_mouth_type" VALUES(3,1,13);
INSERT INTO "mini_mouth_type" VALUES(4,1,14);
INSERT INTO "mini_mouth_type" VALUES(5,2,1);
INSERT INTO "mini_mouth_type" VALUES(6,1,2);
INSERT INTO "mini_mouth_type" VALUES(7,1,17);
INSERT INTO "mini_mouth_type" VALUES(8,1,14);
INSERT INTO "mini_mouth_type" VALUES(9,2,15);
INSERT INTO "mini_mouth_type" VALUES(10,1,10);
INSERT INTO "mini_mouth_type" VALUES(11,2,0);
INSERT INTO "mini_mouth_type" VALUES(12,2,1);
INSERT INTO "mini_mouth_type" VALUES(13,2,3);
INSERT INTO "mini_mouth_type" VALUES(14,2,4);
INSERT INTO "mini_mouth_type" VALUES(15,1,16);
INSERT INTO "mini_mouth_type" VALUES(16,2,1);
INSERT INTO "mini_mouth_type" VALUES(17,2,18);
INSERT INTO "mini_mouth_type" VALUES(18,1,17);
INSERT INTO "mini_mouth_type" VALUES(19,1,2);
INSERT INTO "mini_mouth_type" VALUES(20,1,2);
INSERT INTO "mini_mouth_type" VALUES(21,1,2);
INSERT INTO "mini_mouth_type" VALUES(22,1,2);
INSERT INTO "mini_mouth_type" VALUES(23,1,2);
INSERT INTO "mini_mouth_type" VALUES(24,1,2);
INSERT INTO "mini_mouth_type" VALUES(25,1,2);
INSERT INTO "mini_mouth_type" VALUES(26,1,2);
INSERT INTO "mini_mouth_type" VALUES(27,1,2);
INSERT INTO "mini_mouth_type" VALUES(28,1,2);
INSERT INTO "mini_mouth_type" VALUES(29,1,2);
INSERT INTO "mini_mouth_type" VALUES(30,1,2);
INSERT INTO "mini_mouth_type" VALUES(31,1,2);
COMMIT;